Repository banzaicloud/banzai-cli, pull requests merged in 2020-02, with the labels that each got.

#199 [Logging] Fix default Secret and Bucket selection in case of interactive mode
  internal/cli/command/cluster/integratedservice/services/logging/activate.go
Labels: integrated-services

#202 Terraform init backend config
  .gitignore
  internal/cli/command/controlplane/exec.go
  internal/cli/command/controlplane/utils.go
Labels: enhancement

#201 Service command refactor
  internal/cli/command/cluster/integratedservice/cmd.go
  internal/cli/command/cluster/integratedservice/list.go
  internal/cli/command/cluster/integratedservice/services/activate.go
  internal/cli/command/cluster/integratedservice/services/common.go
  internal/cli/command/cluster/integratedservice/services/deactivate.go
  internal/cli/command/cluster/integratedservice/services/dns/common.go
  internal/cli/command/cluster/integratedservice/services/dns/get.go
  internal/cli/command/cluster/integratedservice/services/dns/manager.go
  internal/cli/command/cluster/integratedservice/services/dns/update.go
  internal/cli/command/cluster/integratedservice/services/expiry/common.go
  internal/cli/command/cluster/integratedservice/services/expiry/get.go
  internal/cli/command/cluster/integratedservice/services/expiry/manager.go
  internal/cli/command/cluster/integratedservice/services/expiry/spec.go
  internal/cli/command/cluster/integratedservice/services/expiry/update.go
  internal/cli/command/cluster/integratedservice/services/get.go
  internal/cli/command/cluster/integratedservice/services/logging/common.go
  internal/cli/command/cluster/integratedservice/services/logging/get.go
  internal/cli/command/cluster/integratedservice/services/logging/manager.go
  internal/cli/command/cluster/integratedservice/services/logging/update.go
  internal/cli/command/cluster/integratedservice/services/monitoring/common.go
  internal/cli/command/cluster/integratedservice/services/monitoring/get.go
  internal/cli/command/cluster/integratedservice/services/monitoring/manager.go
  internal/cli/command/cluster/integratedservice/services/monitoring/update.go
  internal/cli/command/cluster/integratedservice/services/securityscan/activate.go
  internal/cli/command/cluster/integratedservice/services/securityscan/common.go
  internal/cli/command/cluster/integratedservice/services/securityscan/get.go
  internal/cli/command/cluster/integratedservice/services/securityscan/manager.go
  internal/cli/command/cluster/integratedservice/services/securityscan/subcommand.go
  internal/cli/command/cluster/integratedservice/services/securityscan/update.go
  internal/cli/command/cluster/integratedservice/services/subcommand_dns.go
  internal/cli/command/cluster/integratedservice/services/subcommand_expiry.go
  internal/cli/command/cluster/integratedservice/services/subcommand_logging.go
  internal/cli/command/cluster/integratedservice/services/subcommand_monitoring.go
  internal/cli/command/cluster/integratedservice/services/subcommand_vault.go
  internal/cli/command/cluster/integratedservice/services/update.go
  internal/cli/command/cluster/integratedservice/services/vault/common.go
  internal/cli/command/cluster/integratedservice/services/vault/get.go
  internal/cli/command/cluster/integratedservice/services/vault/manager.go
  internal/cli/command/cluster/integratedservice/services/vault/update.go
Labels: tech-debt
